<?php
/**
 * EnvelopeEvent
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocuSign\eSign
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\eSign\Model;

use \ArrayAccess;
/**
 * EnvelopeEvent Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     DocuSign\eSign
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EnvelopeEvent implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'envelope_event_status_code' => 'string',
        'include_documents' => 'string'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'envelope_event_status_code' => 'envelopeEventStatusCode',
        'include_documents' => 'includeDocuments'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'envelope_event_status_code' => 'setEnvelopeEventStatusCode',
        'include_documents' => 'setIncludeDocuments'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'envelope_event_status_code' => 'getEnvelopeEventStatusCode',
        'include_documents' => 'getIncludeDocuments'
    );
  
    
    /**
      * $envelope_event_status_code he envelope status, this can be Sent, Delivered, Completed, Declined, or Voided.
      * @var string
      */
    protected $envelope_event_status_code;
    
    /**
      * $include_documents When set to **true**, the PDF documents are included in the message along with the updated XML.
      * @var string
      */
    protected $include_documents;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->envelope_event_status_code = $data["envelope_event_status_code"];
            $this->include_documents = $data["include_documents"];
        }
    }
    
    /**
     * Gets envelope_event_status_code
     * @return string
     */
    public function getEnvelopeEventStatusCode()
    {
        return $this->envelope_event_status_code;
    }
  
    /**
     * Sets envelope_event_status_code
     * @param string $envelope_event_status_code he envelope status, this can be Sent, Delivered, Completed, Declined, or Voided.
     * @return $this
     */
    public function setEnvelopeEventStatusCode($envelope_event_status_code)
    {
        
        $this->envelope_event_status_code = $envelope_event_status_code;
        return $this;
    }
    
    /**
     * Gets include_documents
     * @return string
     */
    public function getIncludeDocuments()
    {
        return $this->include_documents;
    }
  
    /**
     * Sets include_documents
     * @param string $include_documents When set to **true**, the PDF documents are included in the message along with the updated XML.
     * @return $this
     */
    public function setIncludeDocuments($include_documents)
    {
        
        $this->include_documents = $include_documents;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\DocuSign\eSign\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\DocuSign\eSign\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
